- name: COPYING MONGO.REPO FILE
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/
    #remote_src: yes
- name: INSTALLING MONGO DB
  dnf:
    name: mongodb-org
    state: present
- name: MONGO START
  service:
    name: mongod
    state: started
    enabled: yes
- name: MONGO.conf Edit
  replace: 
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: RESTART MONGOD
